### ISSUE TITLE
ethos: suit_update example stalls 

### ISSUE THREAD

**Issue by emmanuelsearch** [future-proof-iot/RIOT#3]
#### Description

I get stuck when I follow the readme of the example, when I start ethos.
(note: if I remove `USEMODULE += gnrc_uhcpc` from the makefile, it is does not get stuck)

#### Steps to reproduce the issue
on SAMR21 follow the [readme](https://github.com/future-proof-iot/RIOT/tree/suit/examples/suit_update#setup-network)

#### Expected results
Able to update as depicted in the README of the example.

#### Actual results
gets stuck on as shown below:
```
RIOT/dist/tools/ethos$ sudo ./start_network.sh /dev/ttyACM0 riot0 fd00::1/64
net.ipv6.conf.riot0.forwarding = 1
net.ipv6.conf.riot0.accept_ra = 0
----> ethos: sending hello.
----> ethos: activating serial pass through.
----> ethos: hello received
----> ethos: hello received
----> ethos: hello received
----> ethos: hello received
----> ethos: hello received
----> ethos: hello received
----> ethos: hello received
----> ethos: hello received
----> ethos: hello received
----> ethos: hello received
----> ethos: hello received
----> ethos: hello received
----> ethos: hello received
----> ethos: hello received
```

#### Versions
suit branch

**Comment by kaspar030** [comment]
did you re-flash the bootloader?

**Comment by emmanuelsearch** [comment]
yes. And I verified that 
- the shell works with tests/shell, 
- tests/riotboot also works fine on the same board
- a single instance of ethos is running, and 
- I get the same issue on 2 different samr21 boards.

**Comment by fjmolinas** [comment]
I wasn't able to reproduce the issue. Maybe try cleaning and recompiling ethos and uhcpd?

**Comment by emmanuelsearch** [comment]
tried make clean in ethos and uhcpd, does not change anything to the issue on my end.

**Comment by fjmolinas** [comment]
Do you get the same issue when setting up a Border Router like in https://github.com/RIOT-OS/RIOT/tree/master/examples/gnrc_border_router?

**Comment by emmanuelsearch** [comment]
with @kaspar030 we narrowed it down to the RAM being too tight, depending on the compiler. Slightly diminishing the pkt_buf size fixes this. Commit on the way.

**Comment by kaspar030** [comment]
- directly pushed a fix to the suit branch.
