### ISSUE TITLE
suit: url are to long for net_sock_util

### ISSUE THREAD

**Issue by fjmolinas** [future-proof-iot/RIOT#9]
#### Description

When playing around with the extension and naming of the manifest I found that when extending the url by two bytes I got the following error:

```
2019-05-20 16:48:19,061 - INFO # suit_coap: trigger received
2019-05-20 16:48:19,072 - INFO # suit_coap: downloading "coap://[fd00:dead:beef::1]/fw/samr21-xpro/tests_suit_update-riot.suitv4_signed.latest-1.bin"
2019-05-20 16:48:19,073 - INFO # urlpath: �Durlsplit
2019-05-20 16:48:19,076 - INFO # suit_coap: error getting manifest
```

Looking into it `len("fw/samr21-xpro/tests_suit_update-riot.suitv4_signed.latest-1.bin") = 65` and 
https://github.com/future-proof-iot/RIOT/blob/59b4dcffed6b8f32e6fba01e262e941d7413f7ca/sys/include/net/sock/util.h#L107-L108  

#### Steps to reproduce the issue

Change the signed manifest extension. Publish new firmware

#### Proposed Fixes

* Simply define a bigger value
* When calling `make` define a `CFLAGS` for `SOCK_URLPATH_MAXLEN` that is calculated from the size of the URL extension (with some kind of maximum value).

What do you think?

**Comment by fjmolinas** [comment]
Wrong button, I'll Implement and PR before asking for feedback.

**Comment by kaspar030** [comment]
First of all the defines need to be overridable... https://github.com/RIOT-OS/RIOT/pull/11558
